**Learning Pandas**

https://www.kaggle.com/learn/pandas

In [1]:
import pandas as pd

**Creating, Reading and Writing**

Creating:

There are 2 core objects in pandas:
- DataFrame
- Series


DataFrame - A table containing an array of entries where each entry responds to a row/record and a column which is a Series

Series - A sequence of data values like a list

**DataFrame**

In [ ]:
# Creating a DataFrame

# Data Frames take in a dictionary where keys are the column names 
# and the values are a list of entries
pd.DataFrame({"Yes": [100, 200], "No": [400, 500]})

   Yes   No
0  100  400
1  200  500

In [8]:
# Custom row labels (indexes) when creating a DF as by default its labels them as increasing numbers

pd.DataFrame({"Yes": [100, 200], "No": [400, 500]}, index=["Product A", "Product B"])

           Yes   No
Product A  100  400
Product B  200  500

**Series**

In [10]:
# Creating a Series

pd.Series([1,2,3,4,5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [21]:
# Custom row labels (indexes)
pd.Series([1,2,3], index=["milk", "bread", "chocolate"], name="Items")

milk         1
bread        2
chocolate    3
Name: Items, dtype: int64

**Reading data files**

In [13]:
# Reading a dataset into a DataFrame

wine_reviews = pd.read_csv("../../datasets/wine-reviews/winemag-data-130k-v2.csv")

In [ ]:
# Getting shape of DF

# (rows/records, columns/series)
wine_reviews.shape

(129971, 14)

In [ ]:
# Getting Columns of DF

wine_reviews.columns

In [15]:
# Get first 5 rows to see part of the DF

wine_reviews.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [20]:
# Above shows the dataset already has an index column but pandas has added its own
# we can make pandas use the premade column for the index instead of creating a new one

wine_reviews = pd.read_csv("../../datasets/wine-reviews/winemag-data-130k-v2.csv", index_col=0)
wine_reviews.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

**Writing**

In [33]:
# Writings a DF to a csv file

df = pd.DataFrame({"Col 1": [1, 2], "Col 2": [2, 4]}, index=["Row 1", "Row 2"])
print(df)
print()

df.to_csv("save.csv")

df_read = pd.read_csv("save.csv", index_col=0)
print(df_read)

       Col 1  Col 2
Row 1      1      2
Row 2      2      4

       Col 1  Col 2
Row 1      1      2
Row 2      2      4