**Learning Pandas Grouping and Sorting**

https://www.kaggle.com/code/residentmario/grouping-and-sorting

In [2]:
import pandas as pd

reviews = pd.read_csv("../../datasets/wine-reviews/winemag-data-130k-v2.csv", index_col=0)
reviews.columns

Index(['country', 'description', 'designation', 'points', 'price', 'province',
       'region_1', 'region_2', 'taster_name', 'taster_twitter_handle', 'title',
       'variety', 'winery'],
      dtype='str')

**Groupwise analysis**

Using .groupby() - Its creates groups (DataFrame like objects) for every group (a slice of the original DF)

In [9]:
# Using .groupby() as .value_counts()

# .groupby() groups all rows that have the same value in the "points column"
#  then the points column is selected for each group
# .count() then counts the number of non-null values in the "points" column inside each group
reviews.groupby("points").points.count()

points
80       397
81       692
82      1836
83      3025
84      6480
85      9530
86     12600
87     16933
88     17207
89     12226
90     15410
91     11359
92      9613
93      6489
94      3758
95      1535
96       523
97       229
98        77
99        33
100       19
Name: points, dtype: int64

In [13]:
# Any of the sumary funcs are available to use on grouped data

# Using .min()
print(reviews.groupby("points")["price"].min())
print()

# Using apply to get access to each sliced and grouped DF
reviews.groupby("taster_name").apply(lambda df: df.loc[df["points"].idxmax(), "title"])

points
80      5.0
81      5.0
82      4.0
83      4.0
84      4.0
85      4.0
86      4.0
87      5.0
88      6.0
89      7.0
90      8.0
91      7.0
92     11.0
93     12.0
94     13.0
95     20.0
96     20.0
97     35.0
98     50.0
99     44.0
100    80.0
Name: price, dtype: float64

taster_name
Alexander Peartree    Lovingston 2012 Josie's Knoll Merlot (Monticello)
Anna Lee C. Iijima    Robert Weil 2015 Kiedrich Gräfenberg Trockenbe...
Anne Krebiehl MW      Kracher 2013 Trockenbeerenauslese Nummer 5 Zwi...
Carrie Dykes              King Family 2015 Orange Viognier (Monticello)
Christina Pickard             Torbreck 2006 The Struie Shiraz (Barossa)
Fiona Adams           Creekside Cellars 2014 Colorado's Cabernet Fra...
Jeff Jenssen          Royal Tokaji 2013 6 Puttonyos Aszú Gold Label ...
Jim Gordon            Schramsberg 1999 J. Schram 50 Late Disgorged  ...
Joe Czerwinski        Chambers Rosewood Vineyards NV Rare Muscat (Ru...
Kerin O’Keefe         Biondi Santi 2010 Riserva  (Brunello di Montal...
Lauren Buzzeo             De Toren 2014 Book 17 XVII Red (Stellenbosch)
Matt Kettmann         Roar 2014 Garys' Vineyard Pinot Noir (Santa Lu...
Michael Schachner     Emilio Moro 2009 Clon de la Familia  (Ribera d...
Mike DeSimone         Recanati 2011 Reserve David Vineyard Cabernet ...
Paul Gregutt          Charles Smith 2006 Royal City Syrah (Columbia ...
Roger Voss                                  Krug 2002 Brut  (Champagne)
Sean P. Sullivan      Horsepower 2012 Sur Echalas Vineyard Grenache ...
Susan Kostrzewa       Royal Tokaji 1999 Mézes Mály Aszú 6 Puttonyos ...
Virginie Boone                   Alpha Omega 2012 ERA Red (Napa Valley)
dtype: str

In [16]:
# grouping by more than one column
# doing this creates a multi-index for each grouping

reviews.groupby(["country", "points"])["price"].max()

country    points
Argentina  80         35.0
           81         37.0
           82         34.0
           83        125.0
           84         64.0
                     ...
Uruguay    88        120.0
           89         52.0
           90        130.0
           91         60.0
           92         43.0
Name: price, Length: 463, dtype: float64

In [14]:
# Using .agg() summary func

reviews.groupby("points")["price"].agg([len, min, max])

          len   min     max
points
80        397   5.0    69.0
81        692   5.0   130.0
82       1836   4.0   150.0
83       3025   4.0   225.0
84       6480   4.0   225.0
85       9530   4.0   320.0
86      12600   4.0   170.0
87      16933   NaN     NaN
88      17207   6.0  3300.0
89      12226   7.0   500.0
90      15410   NaN     NaN
91      11359   7.0  2013.0
92       9613  11.0   750.0
93       6489  12.0   770.0
94       3758  13.0  1125.0
95       1535  20.0   973.0
96        523  20.0  2500.0
97        229  35.0  2000.0
98         77  50.0  1900.0
99         33  44.0   850.0
100        19  80.0  1500.0

**Multi-indexes**

when using groupby it can sometimes lead to multi idnexes when grouping by more than one column

In [24]:
# Example of multi-indexed df

df = reviews.groupby(["country", "points"])["price"].max()
print(df)
print()

print(type(df.index))

country    points
Argentina  80         35.0
           81         37.0
           82         34.0
           83        125.0
           84         64.0
                     ...
Uruguay    88        120.0
           89         52.0
           90        130.0
           91         60.0
           92         43.0
Name: price, Length: 463, dtype: float64

<class 'pandas.MultiIndex'>

In [31]:
# converting multi-index back to regular index

df = df.reset_index()
df

     index    country  points  price
0        0  Argentina      80   35.0
1        1  Argentina      81   37.0
2        2  Argentina      82   34.0
3        3  Argentina      83  125.0
4        4  Argentina      84   64.0
..     ...        ...     ...    ...
458    458    Uruguay      88  120.0
459    459    Uruguay      89   52.0
460    460    Uruguay      90  130.0
461    461    Uruguay      91   60.0
462    462    Uruguay      92   43.0

[463 rows x 4 columns]

**Sorting**

Generally returned data is displayed based on index order not value orders such as a value for a column

sort_values() allow sorting to happen

In [33]:
# using .sort_values()

print(df)
print()

print(df.sort_values(by="price"))

     index    country  points  price
0        0  Argentina      80   35.0
1        1  Argentina      81   37.0
2        2  Argentina      82   34.0
3        3  Argentina      83  125.0
4        4  Argentina      84   64.0
..     ...        ...     ...    ...
458    458    Uruguay      88  120.0
459    459    Uruguay      89   52.0
460    460    Uruguay      90  130.0
461    461    Uruguay      91   60.0
462    462    Uruguay      92   43.0

[463 rows x 4 columns]

     index   country  points   price
331    331  Portugal      80     8.0
74      74  Bulgaria      85     9.0
71      71  Bulgaria      82     9.0
70      70  Bulgaria      80     9.0
448    448   Ukraine      86     9.0
..     ...       ...     ...     ...
434    434        US      91  2013.0
155    155    France      96  2500.0
147    147    France      88  3300.0
57      57   Austria      98     NaN
131    131     Egypt      84     NaN

[463 rows x 4 columns]

In [34]:
# sort by index values is same as .sort_values()

df.sort_index()

     index    country  points  price
0        0  Argentina      80   35.0
1        1  Argentina      81   37.0
2        2  Argentina      82   34.0
3        3  Argentina      83  125.0
4        4  Argentina      84   64.0
..     ...        ...     ...    ...
458    458    Uruguay      88  120.0
459    459    Uruguay      89   52.0
460    460    Uruguay      90  130.0
461    461    Uruguay      91   60.0
462    462    Uruguay      92   43.0

[463 rows x 4 columns]